sudo: required
env: FILEBEAT_VERSION: 5.x
before_install:
  # Install latest version docker CE
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-engine
services:
  - docker

script:
  - docker build --rm --no-cache --build-arg FILEBEAT_VERSION=${FILEBEAT_VERSION} -t quay.io/shazchaudhry/docker-filebeat:${FILEBEAT_VERSION} .
  - docker images
  - docker inspect quay.io/shazchaudhry/docker-filebeat:${FILEBEAT_VERSION}
  - docker login -u="shazchaudhry" -p=${QUAY_PASSWORD} quay.io
  - docker push quay.io/shazchaudhry/docker-filebeat:${FILEBEAT_VERSION}
