sudo: required
env:
  - FILEBEAT_VERSION=5.x
before_install:
  # Install latest version docker CE
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-engine
  - docker --version
  # Build Filebeat image
  - docker build --rm --no-cache --build-arg FILEBEAT_VERSION=${FILEBEAT_VERSION} --tag quay.io/shazchaudhry/docker-filebeat:${FILEBEAT_VERSION} .
  # Install latest version of docker-compose
  #- sudo apt-get update -qq
  #- sudo apt-get install -qq python-pip && pip install --upgrade pip
  #- sudo pip install docker-compose
  #- docker-compose version
  # craete a SDN
  - docker network create -d bridge filebeatSDN
  # Deploy Elasticsearch for testing Filebeat
  - docker run -d --rm --name elasticsearch --network=filebeatSDN --publish 9200:9200 docker.elastic.co/elasticsearch/elasticsearch:5.4.0
  - docker image ls
services:
  - docker

before_script:
  - sleep 120

script:
  - docker run -d --rm --name filebeat --network=filebeatSDN --volume filebeat_data:/var/lib/filebeat --volume $PWD/var/jenkins_home:/var/jenkins_home --env HOST=elasticsearch --env PORT=9200 --env PROTOCOL=http --env USERNAME=elastic --env PASSWORD=changeme quay.io/shazchaudhry/docker-filebeat:${FILEBEAT_VERSION}
  - docker ps -a
  - sleep 60
  - docker exec -it filebeat ls -latr /var/jenkins_home

after_script:
  - docker login -u="shazchaudhry" -p=${QUAY_PASSWORD} quay.io
  - docker push quay.io/shazchaudhry/docker-filebeat:${FILEBEAT_VERSION}
