
filebeat.prospectors:
- type: log
  enabled: true
  paths:
    - /var/*/jobs/*/builds/*/log
    - /var/*/jobs/*/jobs/*/branches/*/builds/*/log
  multiline.pattern: ^\[
  multiline.match: after

#-------------------------- Elasticsearch output ------------------------------
output.elasticsearch:
  hosts: ["localhost:9200"]
  username: elastic
  password: changeme

#============================== Dashboards =====================================
setup.dashboards.enabled: true
# setup.kibana:
#   host: "kibana:5601"
#   username: elastic
#   password: changeme
