
filebeat.prospectors:
- input_type: log
  paths:
    - /var/*/jobs/*/builds/*/log
    - /var/*/jobs/*/jobs/*/branches/*/builds/*/log
  multiline.pattern: ^\[
  multiline.match: after

#-------------------------- Elasticsearch output ------------------------------
output.elasticsearch:
  hosts: ["${HOST}:${PORT}"]
  protocol: "${PROTOCOL}"
  username: "${USERNAME}"
  password: "${PASSWORD}"

#============================== Dashboards =====================================
dashboards.enabled: true
